# Generated by Django 5.0.6 on 2024-06-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('size', models.CharField(max_length=3)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
